version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgresdb
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8003:8002"
  postgresdb:
    image: 'postgres:15'
    hostname: 'distributor'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5434:5432'
    volumes:
      - distributor-postgres-data:/var/lib/postgresql/data
volumes:
  distributor-postgres-data: